
# This file is used to configure the Supabase project

# The Supabase project ID
project_id = "yiitqkjrbskxumriujrh"

[api]
# Port to use for the API URL
port = 54321
# Schemas to expose in your API
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search path of every request
extra_search_path = ["public", "extensions"]
# The maximum number of rows to return from a view, table, or stored procedure
max_rows = 1000

[db]
# Port to use for the local database URL
port = 54322
# The database major version to use
major_version = 15

[studio]
# Port to use for Supabase Studio
port = 54323

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the web interface.
[inbucket]
# Port to use for the email testing server web interface
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
# The maximum file size allowed (e.g. "5MB", "500KB")
file_size_limit = "50MiB"

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 (1 week).
jwt_expiry = 3600
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email
# addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

# Custom OAuth providers. Keys for each provider, in the format `provider = { key = "value", ... }`.
# See https://supabase.com/docs/guides/auth#oauth-providers for details on supported providers and
# their required keys. You must also enable the provider in the Dashboard, for the production
# environment, in the Auth settings page.
[auth.external.apple]
[auth.external.azure]
[auth.external.bitbucket]
[auth.external.discord]
[auth.external.facebook]
[auth.external.github]
[auth.external.gitlab]
[auth.external.google]
[auth.external.keycloak]
[auth.external.linkedin]
[auth.external.notion]
[auth.external.slack]
[auth.external.spotify]
[auth.external.twitch]
[auth.external.twitter]
[auth.external.workos]

# Configure Edge Functions
[functions]
[functions.vertex-ai]
verify_jwt = false
[functions.google-tts]
verify_jwt = false
[functions.google-nlp]
verify_jwt = false
[functions.google-stt]
verify_jwt = false
[functions.content-safety]
verify_jwt = false
