// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yiitqkjrbskxumriujrh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpaXRxa2pyYnNreHVtcml1anJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NDk1MzEsImV4cCI6MjA1OTUyNTUzMX0.Xx95aUUYuK6Z6hAEQWLDlWCMu8Gt0Kl21yY0-yn3xRM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);